waypoints:
  - name: "goal1"
    position:
      x: 2.14
      y: -2.26
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: 0.0

  - name: "goal2"
    position:
      x: 9.17
      y: -1.86
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: 0.0

  - name: "goal4"
    position:
      x: 3.67
      y: 4.5
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: 0.0

  - name: "goal5"
    position:
      x: 6.0
      y: 7.5
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: 0.0

  - name: "goal6"
    position:
      x: -2.0
      y: 2.0
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: 0.0
  
  - name: "goal7"
    position:
      x: -3.5
      y: 6.0
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: 0.0

  - name: "goal8"
    position:
      x: -4.0
      y: -2.0
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: 0.0

  - name: "goal9"
    position:
      x: -9.0
      y: -8.0
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: 0.0