<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rover_gazebo">

<xacro:macro name="rover_wheels_sim" params="left_joint right_joint prefix">
    <link name="${prefix}_fr_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="-1.57 0 0" />
            <geometry>
                <mesh filename="file://$(find rover_description_pkg)/meshes/pro_tire.dae" scale="0.5 0.5 1.0"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="-1.57 0 0" />
            <geometry>
                <cylinder radius="${total_height/2}" length="${track_width}"/>
            </geometry>
        </collision>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${wheel_mass}" />
            <inertia ixx="0.005645" ixy="0.0"  ixz="0.0" iyy= "0.01008" iyz="0.0" izz="0.005645"/>
        </inertial>
        <mu>5.0</mu>
    </link>
    <joint name="${prefix}_fr_wheel_to_base" type="continuous">
        <parent link="${prefix}_base_link"/> 
        <child link="${prefix}_fr_wheel_link"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${wheel_x_offset + front_flipper_x_offset} ${-wheel_y_offset} 0" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}_fl_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="1.57 0 0" />
            <geometry>
                <mesh filename="file://$(find rover_description_pkg)/meshes/pro_tire.dae" scale="0.5 0.5 1.0"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="1.57 0 0" />
            <geometry>
                <cylinder radius="${total_height/2}" length="${track_width}"/>
            </geometry>
        </collision>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${wheel_mass}" />
            <inertia ixx="0.005645" ixy="0.0"  ixz="0.0" iyy= "0.01008" iyz="0.0" izz="0.005645"/>
        </inertial>
        <mu>5.0</mu>
    </link>
    <joint name="${prefix}_fl_wheel_to_base" type="continuous">
        <parent link="${prefix}_base_link"/>
        <child link="${prefix}_fl_wheel_link"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${wheel_x_offset + front_flipper_x_offset} ${wheel_y_offset} 0" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}_rr_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="1.57 0 3.1415" />
            <geometry>
                <mesh filename="file://$(find rover_description_pkg)/meshes/pro_tire.dae" scale="0.5 0.5 1.0"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="1.57 0 3.1415" />
            <geometry>
                <cylinder radius="${total_height/2}" length="${track_width}"/>
            </geometry>
        </collision>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${wheel_mass}" />
            <inertia ixx="0.005645" ixy="0.0"  ixz="0.0" iyy= "0.01008" iyz="0.0" izz="0.005645"/>
        </inertial>
        <mu>5.0</mu>
    </link>
    <joint name="${prefix}_rr_wheel_to_base" type="continuous">
        <parent link="${prefix}_base_link"/>
        <child link="${prefix}_rr_wheel_link"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${-wheel_x_offset} ${-wheel_y_offset} 0"/>
    </joint>

    <link name="${prefix}_rl_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="-1.57 0 3.1415" />
            <geometry>
                <mesh filename="file://$(find rover_description_pkg)/meshes/pro_tire.dae" scale="0.5 0.5 1.0"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="-1.57 0 3.1415" />
            <geometry>
                <cylinder radius="${total_height/2}" length="${track_width}"/>
            </geometry>
        </collision>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${wheel_mass}" />
            <inertia ixx="0.005645" ixy="0.0"  ixz="0.0" iyy= "0.01008" iyz="0.0" izz="0.005645"/>
        </inertial>
        <mu>5.0</mu>
    </link>
    <joint name="${prefix}_rl_wheel_to_base" type="continuous">
        <parent link="${prefix}_base_link"/>
        <child link="${prefix}_rl_wheel_link"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${-wheel_x_offset} ${wheel_y_offset} 0"/>
    </joint>
</xacro:macro>

<!-- Camera -->
<xacro:macro name="camera_gazebo" params="camera_base_frame camera_topic camera_info_topic prefix">
    <xacro:include filename="$(find realsense2_description)/urdf/_d435i.urdf.xacro"/>

    <!-- <xacro:sensor_d435i parent="${camera_base_frame}" use_nominal_extrinsics="true">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:sensor_d435i>  -->


    <joint name="${prefix}_camera_to_payload" type="fixed">
        <origin xyz="0.02 0 ${1 -0.129 - total_height}" rpy="0 0 0"/>
        <parent link="${prefix}_payload_link"/>
        <child link="${prefix}_${camera_base_frame}"/>
    </joint>

    <link name="${prefix}_${camera_base_frame}">
        <visual>
        <origin xyz="0 0 0" rpy="1.57 0 1.57"/>
        <geometry>
                <mesh filename="file://$(find rover_description_pkg)/meshes/realsense.dae "/>
        </geometry>
        </visual>
        <collision>
        <origin xyz="-0.01 0.0 0.0" rpy="0 0 0"/>
        <geometry>
            <box size="0.02 0.1 0.025"/>
        </geometry>
        </collision>        
    </link>   

  <joint name="${prefix}_camera_rgb_joint" type="fixed">
    <origin xyz="0.005 0.018 0.013" rpy="0 0 0"/>
    <parent link="${prefix}_${camera_base_frame}"/>
    <child link="${prefix}_camera_rgb_frame"/>
  </joint>
  <link name="${prefix}_camera_rgb_frame"/>

  <joint name="${prefix}_camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="${prefix}_camera_rgb_frame"/>
    <child link="${prefix}_camera_rgb_optical_frame"/>
  </joint>
  <link name="${prefix}_camera_rgb_optical_frame"/>

  <joint name="${prefix}_camera_depth_joint" type="fixed">
    <origin xyz="0.005 0.028 0.013" rpy="0 0 0"/>
    <parent link="${prefix}_${camera_base_frame}"/>
    <child link="${prefix}_camera_depth_frame"/>
  </joint>
  <link name="${prefix}_camera_depth_frame"/>

  <joint name="${prefix}_camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/> 
    <parent link="${prefix}_camera_depth_frame"/>
    <child link="${prefix}_camera_depth_optical_frame"/>
  </joint>
  <link name="${prefix}_camera_depth_optical_frame"/>

    <gazebo reference="${prefix}_${camera_base_frame}">
        <sensor name="d435_color" type="camera">
            <topic>${prefix}/color/image_raw</topic>
            <ignition_frame_id>${prefix}/camera_link</ignition_frame_id>
            <gz_frame_id>${prefix}/camera_link</gz_frame_id>
            <camera name="d435">
                <camera_info_topic>${prefix}/color/camera_info</camera_info_topic>
                <horizontal_fov>1.21126</horizontal_fov>
				<image>
					<width>640</width>
					<height>480</height>
					<format>RGB_INT8</format>
				</image>
				<clip>
					<near>0.1</near>
					<far>100</far>
				</clip>
				<noise>
					<type>gaussian</type>
					<mean>0</mean>
					<stddev>0.007</stddev>
				</noise>
            </camera>
            <always_on>true</always_on>
            <update_rate>10</update_rate>
            <visualize>true</visualize>
        </sensor>

		<sensor name="d435_depth" type="depth_camera">
			<always_on>1</always_on>
			<update_rate>10</update_rate>
			<visualize>0</visualize>
			<topic>${prefix}/depth/image_raw</topic>
            <ignition_frame_id>${prefix}/camera_depth_optical_frame</ignition_frame_id>
			<pose>0 0.0175 0.5125 0 -0 0</pose>
			<camera name="d435">
                <point_cloud_topic>${prefix}/depth/color/points</point_cloud_topic>
                <camera_info_topic>${prefix}/depth/camera_info</camera_info_topic>
				<horizontal_fov>1.48702</horizontal_fov>
				<image>
					<width>1280</width>
					<height>720</height>
				</image>
				<clip>
					<near>0.1</near>
					<far>100</far>
				</clip>
				<!-- <noise>
					<type>gaussian</type>
					<mean>0</mean>
					<stddev>0.007</stddev>
				</noise> -->
			</camera>
		</sensor>        
    </gazebo>
    <xacro:if value="$(eval prefix == 'master')">
        <gazebo>    
            <plugin filename="libignition-gazebo-sensors-system.so" name="ignition::gazebo::systems::Sensors">
                \<render_engine>ogre2</render_engine>
            </plugin>
        </gazebo>
    </xacro:if>  
</xacro:macro>

    <!-- Gazebo Plugins -->
<xacro:macro name="gazebo_diff_drive_controller" params="left_joint right_joint namespace prefix">

    <gazebo>
        <plugin name="ignition::gazebo::systems::DiffDrive" filename="ignition-gazebo-diff-drive-system"> 
            <num_wheel_pairs>2</num_wheel_pairs>
            <!-- Wheel Information -->
            <left_joint>${prefix}_rl_wheel_to_base</left_joint>
            <left_joint>${prefix}_fl_wheel_to_base</left_joint>
            <right_joint>${prefix}_rr_wheel_to_base</right_joint>
            <right_joint>${prefix}_fr_wheel_to_base</right_joint>
            <wheel_separation>0.37</wheel_separation>
            <wheel_radius>0.102</wheel_radius>

            <!-- Limits -->
            <max_linear_acceleration>5</max_linear_acceleration>
            <min_linear_acceleration>-5</min_linear_acceleration>
            <max_angular_acceleration>4</max_angular_acceleration>
            <min_angular_acceleration>-4</min_angular_acceleration>

            
            <!-- Output -->
            <frame_id>${namespace}odom</frame_id>
            <child_frame_id>/${prefix}_base_link</child_frame_id>

            <!-- Topics -->
            <topic>/${namespace}cmd_vel</topic>
            <odom_topic>/${namespace}odom/wheels</odom_topic>
            <tf_topic>/${namespace}tf_gazebo</tf_topic>



        </plugin>

        <plugin filename="ignition-gazebo-joint-state-publisher-system" name="ignition::gazebo::systems::JointStatePublisher">
            <topic>/${namespace}joint_states</topic>
        </plugin>      

    </gazebo>
</xacro:macro>



<xacro:macro name="gazebo_wheel_contact" params="prefix">
    <gazebo reference="${prefix}_diff_wheel_left">
        <mu1 value="1.0"/>
        <mu2 value="1.0"/>
        <kp value="1e15"/>
        <kd value="1e13"/>
        <fdir1 value="0 0 1"/>
    </gazebo>

    <gazebo reference="${prefix}_diff_wheel_right">
        <mu1 value="1.0"/>
        <mu2 value="1.0"/>
        <kp value="1e15"/>
        <kd value="1e13"/>
        <fdir1 value="0 0 1"/>
    </gazebo>

    <gazebo reference="${prefix}_collision_f_l">
        <mu1 value="0.1"/>
        <mu2 value="0.1"/>
        <kp value="10000000.0"/>
        <kd value="100.0"/>
        <minDepth>0.001</minDepth>
    </gazebo>

    <gazebo reference="${prefix}_collision_f_r">
        <mu1 value="0.1"/>
        <mu2 value="0.1"/>
        <kp value="10000000.0"/>
        <kd value="100.0"/>
        <minDepth>0.001</minDepth>
    </gazebo>

    <gazebo reference="${prefix}_collision_b_l">
        <mu1 value="0.1"/>
        <mu2 value="0.1"/>
        <kp value="10000000.0"/>
        <kd value="100.0"/>
        <minDepth>0.001</minDepth>
    </gazebo>

    <gazebo reference="${prefix}_collision_b_r">
        <mu1 value="0.1"/>
        <mu2 value="0.1"/>
        <kp value="10000000.0"/>
        <kd value="100.0"/>
        <minDepth>0.001</minDepth>
    </gazebo>
</xacro:macro>




    
</robot>